### ISSUE TITLE
Swift 1.2 not compatible

### ISSUE THREAD

**Issue by Miller47** [exchangegroup/Cosmos#2]
I am working on a project using Swift 1.2 and am unable to use Cosmos is there a 1.2 compatible version still available?

**Comment by evgenyneu** [comment]
Hi, @Miller47, sorry, it is Swift 2.0 / Xcode 7 only. There are many great alternatives mentioned in the [readme](https://github.com/exchangegroup/Cosmos#alternative-solutions).

**Comment by Miller47** [comment]
Okay, I found one. I just liked yours the most as it seemed like the most featured and documented of all of them. Keep up the great work!

**Comment by evgenyneu** [comment]
@Miller47 thank you.

**Comment by evgenyneu** [comment]
Support for Xcode 6 has been added by [nickhart](https://github.com/nickhart).

Here are the setup instructions.

https://github.com/exchangegroup/Cosmos/wiki/Swift-1.2-setup
