### ISSUE TITLE
Custom image?

### ISSUE THREAD

**Issue by andrew8712** [exchangegroup/Cosmos#5]
Your library is a great example of modern iOS control, I really appreciate your effort!

Is there an easy way to use a custom images instead of stars?

**Comment by evgenyneu** [comment]
Hi, thank you for your kind words. There is no ability to use an image unfortunately. The starts are drawn at runtime with a shape. One can use a different shape by using the `cosmosView.settings.starPoints` property. It contains an array of points, the size of the whole shape is 100 by 100.
